# Substrate builds in AWS CodeBuild
#
# <https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html>
---
version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
  pre_build:
    commands:
      - date
      - go version
  build:
    commands:
      - date
  post_build:
    commands:
      - date
artifacts:
  files:
    - substrate-*-*-*-*.tar.gz
...
