# Substrate builds in AWS CodeBuild
#
# <https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html>
---
version: 0.2

env:
  variables:
    GO_VERSION: 1.18
    PATH: /go/bin:/root/bin:/root/go/bin:/usr/local/bin:/usr/bin:/bin
    # SLACK_WEBHOOK_URL comes from upstream

phases:
  install:
    commands:
      - mkdir -p "$HOME/bin"
      - curl -o"$HOME/awscli.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      - unzip -q "$HOME/awscli.zip" -d "$HOME"
      - $HOME/aws/install -b "$HOME/bin" -i "$HOME/aws" --update
      - rm -f "$HOME/awscli.zip"
      - curl -L -o"golang.tar.gz" -s "https://redirector.gvt1.com/edgedl/go/go$GO_VERSION.linux-amd64.tar.gz"
      - tar -C"$HOME" -f"golang.tar.gz" -x
      - rm -f "golang.tar.gz"
      - go get "golang.org/x/tools/cmd/goimports"
      - go install "golang.org/x/tools/cmd/goimports"
      - cat "terraform.version" | xargs -I"VERSION" curl -L -o"terraform.zip" -s "https://releases.hashicorp.com/terraform/VERSION/terraform_VERSION_linux_amd64.zip"
      - unzip "terraform.zip" -d "$HOME/bin"
      - rm -f "terraform.zip"
    finally:
      - go run "tools/slack-codebuild/main.go" "install"
  pre_build:
    commands:

      # Ensure build dependencies are in order.
      - go version
      - terraform version

      # Execute go:generate directives and the like, then ensure they haven't
      # introduced changes that should've been committed.
      - make
      - git diff --exit-code

      # Run the tests. Wish there were more.
      - make test

      # Build the binaries and tarballs.
      - make release

      # Write a tree of upgrade breadcrumbs for paying customers.
      - sh "tools/upgrades.sh"

      # End here if everything's been successful but this isn't a tagged build.
      - echo git describe --exact-match --tags "HEAD"

    finally:
      - echo go run "tools/slack-codebuild/main.go" "pre_build"
      - echo sh "tools/tweet-codebuild.sh"
artifacts:
  files:
    - substrate-*-*-*-*.tar.gz
    - upgrade/*-*/*
...
