# Substrate builds in AWS CodeBuild
#
# <https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html>
---
version: 0.2

env:
  variables:
    GO_VERSION: 1.16.3
    PATH: /root/bin:/root/go/bin:/usr/local/bin:/usr/bin:/bin
    TERRAFORM_VERSION: 0.14.7

phases:
  install:
    commands:
      - mkdir -p "$HOME/bin"
      - curl -L -o"golang.tar.gz" -s "https://redirector.gvt1.com/edgedl/go/go$GO_VERSION.linux-amd64.tar.gz"
      - tar -C"$HOME" -f"golang.tar.gz" -x
      - rm -f "golang.tar.gz"
      - curl -L -o"terraform.zip" -s "https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      - unzip "terraform.zip" -d "$HOME/bin"
      - rm -f "terraform.zip"
  pre_build:
    commands:
      - go version
      - terraform version
      - make
      - git diff --exit-code
      - make test
  build:
    commands:
      - make release
  post_build:
    commands:
      - find "." -name "substrate-*-*-*-*-tar.gz" -printf "%P\\n" | xargs -I"___" aws s3api put-object-acl --acl "bucket-owner-full-control" --bucket "$BUCKET" --key "substrate/___"
artifacts:
  files:
    - substrate-*-*-*-*.tar.gz
...
