# Substrate builds in AWS CodeBuild
#
# <https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html>
---
version: 0.2

env:
  variables:
    PATH: /root/bin:/root/.goenv/shims:/root/.goenv/bin:/go/bin:/usr/local/bin:/usr/bin

phases:
  install:
    commands:
      - curl -L -o terraform.zip -s https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      - mkdir ~/bin
      - unzip terraform.zip -d ~/bin
      - rm -f terraform.zip
    runtime-versions:
      golang: 1.16
  pre_build:
    commands:
      - go version
      - terraform version
      - make
      - git diff --exit-code
      - git diff --quiet
      - make test
  build:
    commands:
      - make release
  post_build:
    commands:
      - date
artifacts:
  files:
    - substrate-*-*-*-*.tar.gz
...
