# Substrate builds in AWS CodeBuild
#
# <https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html>
---
version: 0.2

env:
  variables:
    GO_VERSION: 1.21.5
    PATH: /go/bin:/root/bin:/root/go/bin:/usr/local/bin:/usr/bin:/bin
    # SLACK_WEBHOOK_URL comes from upstream

phases:
  install:
    commands:
      - mkdir -p "$HOME/bin"

      # Install the AWS CLI v2.
      - curl -o"$HOME/awscli.zip" -s "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"
      - unzip -q "$HOME/awscli.zip" -d "$HOME"
      - $HOME/aws/install -b "$HOME/bin" -i "$HOME/aws" --update
      - rm -f "$HOME/awscli.zip"

      # Install Go and goimports.
      - curl -L -o"golang.tar.gz" -s "https://redirector.gvt1.com/edgedl/go/go$GO_VERSION.linux-arm64.tar.gz"
      - tar -C"$HOME" -f"golang.tar.gz" -x
      - rm -f "golang.tar.gz"

      # Install our pinned version of Terraform.
      - cat "terraform.version" | xargs -I"VERSION" curl -L -o"terraform.zip" -s "https://releases.hashicorp.com/terraform/VERSION/terraform_VERSION_linux_arm64.zip"
      - unzip "terraform.zip" -d "$HOME/bin"
      - rm -f "terraform.zip"

    finally:
      - go run "tools/slack-codebuild/main.go" "install"
  pre_build:
    commands:

      # Ensure build dependencies are in order.
      - go version
      - terraform version

      # If this is a tagged release, ensure the manual has been published.
      # - sh "tools/ensure-manual-published.sh"

      # Execute go:generate directives and the like, then ensure they haven't
      # introduced changes that should've been committed.
      - make
      - git diff --exit-code

      # Run the tests. Wish there were more.
      - make test

      # Build the binaries and tarballs.
      - make release

      # Write HTML for the /download page and a tree of upgrade breadcrumbs.
      - sh "tools/upgrades.sh"
      - sh "tools/download-html.sh"

    finally:
      - go run "tools/slack-codebuild/main.go" "pre_build"
      - sh "tools/tweet-codebuild.sh"
artifacts:
  files:
    - substrate-*.tar.gz
    - substrate.download.html
    - substrate.version
    - upgrade/*
...
