---
name: Substrate Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write # for aws-actions/configure-aws-credentials
  contents: read

jobs:
  macos-release:
    name: macOS Release

    strategy:
      matrix:
        os: [macos-13, macos-14]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412086678291:role/GitHubActions
          aws-region: us-east-1

      - run: |
          set -x
          pwd
          ls -l
          env
          uname -a
          aws sts get-caller-identity

  release:
    name: Release

    needs: [macos-release, test]

    runs-on: ubuntu-latest

    env:
      #CHANNELS: "${{ secrets.CHANNELS }}"
      CHANNELS: "#random"
      GOBIN: $HOME/.local/bin
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:

      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412086678291:role/GitHubActions
          aws-region: us-east-1

      - run: make release

      - if: always()
        run: |
          go run "tools/slack-codebuild/main.go" "${{ job.status }}"

  test:
    name: Test
    #secrets: inherit
    #uses: ./.github/workflows/test.yml
    runs-on: ubuntu-latest
    steps:
      - run: true # short circuit during workflow testing
...
